import math
import stdio
import sys

# Accept a (float), b (float), and c (float) as command-line arguments.
...
...
...

if ...:
    # If a is 0, write the message "Value of a must not be 0" to standard output.
    ...
else:
    # Compute discriminant (b^2 - 4ac).
    discriminant = ...

    if ...:
        # If discriminant is negative, write the message "Value of discriminant must not be
        # negative" to standard output.
        ...
    else:
        # Compute the two roots of the quadratic equation ax^2 + bx + c = 0.
        root1 = ...
        root2 = ...

        # Write the two roots to standard output, separated by a space.
        ...
